
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "CMakeLists.txt:3 (find_program)"
    mode: "program"
    variable: "CCACHE_PROGRAM"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "ccache"
    candidate_directories:
      - "C:/Users/Administrator/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/"
      - "C:/Users/Administrator/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "G:/Git/cmd/"
      - "G:/cmake/bin/"
      - "C:/Users/Administrator/AppData/Local/Microsoft/WindowsApps/"
      - "C:/msys64/mingw64/bin/"
      - "E:/Microsoft VS Code/bin/"
    searched_directories:
      - "C:/Users/Administrator/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/ccache.com"
      - "C:/Users/Administrator/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/ccache.exe"
      - "C:/Users/Administrator/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/ccache"
      - "C:/Users/Administrator/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/ccache.com"
      - "C:/Users/Administrator/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/ccache.exe"
      - "C:/Users/Administrator/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/ccache"
      - "C:/Windows/System32/ccache.com"
      - "C:/Windows/System32/ccache.exe"
      - "C:/Windows/System32/ccache"
      - "C:/Windows/ccache.com"
      - "C:/Windows/ccache.exe"
      - "C:/Windows/ccache"
      - "C:/Windows/System32/wbem/ccache.com"
      - "C:/Windows/System32/wbem/ccache.exe"
      - "C:/Windows/System32/wbem/ccache"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ccache.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ccache.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ccache"
      - "G:/Git/cmd/ccache.com"
      - "G:/Git/cmd/ccache.exe"
      - "G:/Git/cmd/ccache"
      - "G:/cmake/bin/ccache.com"
      - "G:/cmake/bin/ccache.exe"
      - "G:/cmake/bin/ccache"
      - "C:/Users/Administrator/AppData/Local/Microsoft/WindowsApps/ccache.com"
      - "C:/Users/Administrator/AppData/Local/Microsoft/WindowsApps/ccache.exe"
      - "C:/Users/Administrator/AppData/Local/Microsoft/WindowsApps/ccache"
      - "C:/msys64/mingw64/bin/ccache.com"
      - "C:/msys64/mingw64/bin/ccache.exe"
      - "C:/msys64/mingw64/bin/ccache"
      - "E:/Microsoft VS Code/bin/ccache.com"
      - "E:/Microsoft VS Code/bin/ccache.exe"
      - "E:/Microsoft VS Code/bin/ccache"
    found: false
    search_context:
      ENV{PATH}:
        - "c:\\Users\\Administrator\\AppData\\Roaming\\Code\\User\\globalStorage\\github.copilot-chat\\debugCommand"
        - "c:\\Users\\Administrator\\AppData\\Roaming\\Code\\User\\globalStorage\\github.copilot-chat\\copilotCli"
        - "C:\\Windows\\system32"
        - "C:\\Windows"
        - "C:\\Windows\\System32\\Wbem"
        - "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\"
        - "G:\\Git\\cmd"
        - "G:\\cmake\\bin"
        - "C:\\Users\\Administrator\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\msys64\\mingw64\\bin"
        - "E:\\Microsoft VS Code\\bin"
  -
    kind: "message-v1"
    backtrace:
      - "G:/cmake/share/cmake-4.4/Modules/CMakeDetermineSystem.cmake:218 (message)"
      - "CMakeLists.txt:15 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
...
